/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import React, { useState, useEffect } from 'react';
import { MapPin, Clock, Heart, Users, Search, Navigation, Hotel, Camera, ExternalLink, Loader2, ChevronRight, ChevronDown, Map as MapIcon, Mail, FileText, X } from 'lucide-react';
import { motion, AnimatePresence } from 'motion/react';
import { generateTripPlan, TripPlan, TripRequest } from './services/geminiService';
import { hasActiveApiKey, openApiKeySelector, isUserKeySelected } from './services/aiProvider';
import { buildTripPlanPdf, triggerPdfDownload } from './services/pdfService';
import { uploadTripPdfToSupabase } from './services/supabaseStorage';
import { getAdminTripHistory, getExampleTripHistory, getLocalTripHistory, getOrCreateUserId, saveLocalTripHistory, saveTripHistoryToSupabase, setTripExampleFlag, TripHistoryItem } from './services/tripHistoryService';
import InteractiveMap from './components/InteractiveMap';
import ChatBot from './components/ChatBot';
import clsx from 'clsx';
import { Analytics } from "@vercel/analytics/next"
import { SpeedInsights } from "@vercel/speed-insights/next"

export default function App() {
  const [loading, setLoading] = useState(false);
  const [savingPdf, setSavingPdf] = useState(false);
  const [hasKey, setHasKey] = useState<boolean | null>(null);
  const [routePath, setRoutePath] = useState(() => window.location.pathname);
  const [activeView, setActiveView] = useState<'planner' | 'history' | 'examples'>('planner');
  const [historyItems, setHistoryItems] = useState<TripHistoryItem[]>([]);
  const [adminItems, setAdminItems] = useState<TripHistoryItem[]>([]);
  const [exampleItems, setExampleItems] = useState<TripHistoryItem[]>([]);
  const [examplesLoading, setExamplesLoading] = useState(false);
  const [adminPassword, setAdminPassword] = useState('');
  const [adminUnlocked, setAdminUnlocked] = useState(false);
  const [adminLoading, setAdminLoading] = useState(false);

  useEffect(() => {
    const checkKey = async () => {
      const active = await hasActiveApiKey();
      const userSelected = isUserKeySelected();
      // Show banner when there is no active key or only a shared/system key is in use.
      setHasKey(active && userSelected);
    };
    checkKey();

    setHistoryItems(getLocalTripHistory());
    void refreshExampleTrips();

    const onPopState = () => {
      setRoutePath(window.location.pathname);
    };
    window.addEventListener('popstate', onPopState);

    return () => {
      window.removeEventListener('popstate', onPopState);
    };
  }, []);

  const refreshExampleTrips = async () => {
    setExamplesLoading(true);
    try {
      const items = await getExampleTripHistory();
      setExampleItems(items);
    } catch (error) {
      console.error(error);
      setExampleItems([]);
    } finally {
      setExamplesLoading(false);
    }
  };

  const handleSelectKey = async () => {
    await openApiKeySelector();
    setHasKey(true); // Assume success after opening the selector.
  };

  const [loadingMessageIndex, setLoadingMessageIndex] = useState(0);
  const loadingMessages = [
    "Building your itinerary...",
    "Optimizing the driving route...",
    "Finding interesting sights...",
    "Gathering hotel suggestions...",
    "Preparing your custom plan..."
  ];

  useEffect(() => {
    let interval: NodeJS.Timeout;
    if (loading) {
      setLoadingMessageIndex(0);
      interval = setInterval(() => {
        setLoadingMessageIndex((prev) => (prev + 1) % loadingMessages.length);
      }, 3000);
    }
    return () => clearInterval(interval);
  }, [loading]);

  const [plan, setPlan] = useState<TripPlan | null>(null);
  const [formData, setFormData] = useState<TripRequest>({
    start: 'Halden, Norway',
    destination: 'Termoli, Italy',
    waypoints: '',
    hoursPerDay: 7,
    age: '45',
    interests: 'romance, nature'
  });

  const handleSendEmail = () => {
    if (!plan) return;

    const subject = encodeURIComponent(`Our Trip Plan: ${formData.start} to ${formData.destination}`);
    
    let bodyText = `Hello!\n\nHere is our trip plan generated by ELSK Roadtrip:\n\n`;
    bodyText += `Summary: ${plan.summary}\n\n`;
    
    plan.days.forEach(day => {
      bodyText += `DAY ${day.day}: ${day.route}\n`;
      bodyText += `Sights:\n`;
      day.pois.forEach(poi => {
        bodyText += `- ${poi.name}: ${poi.description} (Link: ${poi.websiteUrl || 'N/A'})\n`;
      });
      bodyText += `Accommodation:\n`;
      day.accommodations.forEach(acc => {
        bodyText += `- ${acc.name}: ${acc.priceEstimate} (Link: ${acc.websiteUrl || 'N/A'})\n`;
      });
      bodyText += `\n`;
    });

    if (plan.googleMapsLink) {
      bodyText += `View the full route in Google Maps: ${plan.googleMapsLink}\n\n`;
    }

    bodyText += `Have a great trip!\nSent from ELSK Roadtrip`;

    const mailtoLink = `mailto:?subject=${subject}&body=${encodeURIComponent(bodyText)}`;
    window.location.href = mailtoLink;
  };

  const persistGeneratedTrip = async (generatedPlan: TripPlan, request: TripRequest) => {
    setSavingPdf(true);
    try {
      const { blob, fileName } = await buildTripPlanPdf(generatedPlan, request);
      const userId = getOrCreateUserId();
      const pdfUrl = await uploadTripPdfToSupabase(blob, fileName, userId);

      const historyItem: TripHistoryItem = {
        id: crypto.randomUUID(),
        createdAt: new Date().toISOString(),
        userId,
        start: request.start,
        destination: request.destination,
        summary: generatedPlan.summary,
        googleMapsLink: generatedPlan.googleMapsLink || '',
        pdfUrl,
        isExample: false,
      };

      saveLocalTripHistory(historyItem);
      setHistoryItems(getLocalTripHistory());

      try {
        await saveTripHistoryToSupabase(historyItem);
      } catch (error) {
        console.error(error);
      }
    } catch (error) {
      alert(error instanceof Error ? error.message : 'Could not auto-save PDF to storage');
    } finally {
      setSavingPdf(false);
    }
  };

  const handleDownloadPdf = async () => {
    if (!plan) return;

    try {
      const { blob, fileName } = await buildTripPlanPdf(plan, formData);
      triggerPdfDownload(blob, fileName);
    } catch (error) {
      alert(error instanceof Error ? error.message : 'Could not download PDF');
    }
  };

  const handleAdminUnlock = async () => {
    const configuredPassword = (import.meta as any).env?.VITE_ADMIN_PASSWORD as string | undefined;

    if (!configuredPassword) {
      alert('Admin password is not configured. Set VITE_ADMIN_PASSWORD in your environment.');
      return;
    }

    if (adminPassword !== configuredPassword) {
      alert('Wrong admin password.');
      return;
    }

    setAdminUnlocked(true);
    setAdminLoading(true);
    try {
      const items = await getAdminTripHistory();
      setAdminItems(items);
    } catch (error) {
      alert(error instanceof Error ? error.message : 'Could not load admin history');
    } finally {
      setAdminLoading(false);
    }
  };

  const handleAdminRefresh = async () => {
    setAdminLoading(true);
    try {
      const items = await getAdminTripHistory();
      setAdminItems(items);
    } catch (error) {
      alert(error instanceof Error ? error.message : 'Could not refresh admin history');
    } finally {
      setAdminLoading(false);
    }
  };

  const handleSetExampleTrip = async (tripId: string, isExample: boolean) => {
    setAdminLoading(true);
    try {
      await setTripExampleFlag(tripId, isExample);
      const [adminHistory, examples] = await Promise.all([
        getAdminTripHistory(),
        getExampleTripHistory(),
      ]);
      setAdminItems(adminHistory);
      setExampleItems(examples);
    } catch (error) {
      alert(error instanceof Error ? error.message : 'Could not update example status');
    } finally {
      setAdminLoading(false);
    }
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    
    // Re-check key before submit.
    const active = await hasActiveApiKey();
    if (!active) {
      await handleSelectKey();
      return;
    }

    setLoading(true);
    try {
      const requestSnapshot = { ...formData };
      const result = await generateTripPlan(requestSnapshot);
      setPlan(result);
      await persistGeneratedTrip(result, requestSnapshot);
    } catch (error) {
      alert(error instanceof Error ? error.message : 'Something went wrong');
    } finally {
      setLoading(false);
    }
  };

  const isAdminRoute = routePath === '/admin';
  const isAboutRoute = routePath === '/about';

  const navigateTo = (path: string) => {
    window.history.pushState({}, '', path);
    setRoutePath(path);
    window.scrollTo({ top: 0, behavior: 'smooth' });
  };

  return (
    <div className="min-h-screen pb-20">
      {/* API Key Banner */}
      <AnimatePresence>
        {hasKey === false && (
          <motion.div 
            initial={{ height: 0, opacity: 0 }}
            animate={{ height: 'auto', opacity: 1 }}
            exit={{ height: 0, opacity: 0 }}
            className="bg-amber-50 border-b border-amber-200 py-3 px-4 text-center sticky top-0 z-50"
          >
            <div className="max-w-4xl mx-auto flex flex-col items-center justify-center gap-2">
              <div className="flex flex-col sm:flex-row items-center gap-3">
                <p className="text-amber-800 text-sm font-medium">
                  For best results and to avoid limits, please choose your own (free) API key.
                </p>
                <button 
                  onClick={handleSelectKey}
                  className="bg-amber-600 hover:bg-amber-700 text-white text-xs font-bold py-1.5 px-4 rounded-full transition-colors shadow-sm"
                >
                  Choose API key
                </button>
              </div>
              <p className="text-amber-700 text-[11px]">
                If the list is empty: go to <a href="https://aistudio.google.com/" target="_blank" rel="noopener noreferrer" className="underline font-bold">AI Studio</a>, click "Get API key", and create one first.
              </p>
            </div>
            <button 
              onClick={() => setHasKey(true)} 
              className="absolute right-4 top-1/2 -translate-y-1/2 text-amber-400 hover:text-amber-600 transition-colors"
            >
              <X size={18} />
            </button>
          </motion.div>
        )}
      </AnimatePresence>

      {/* Hero Section */}
      <header className="relative min-h-[58vh] md:min-h-[64vh] flex items-center overflow-hidden">
        <img
          src="/hero.png"
          alt="Joyful couple driving a red convertible along a coastal highway at sunset"
          className="absolute inset-0 w-full h-full object-cover"
          referrerPolicy="no-referrer"
        />
        <div className="absolute inset-0 bg-gradient-to-t from-black/74 via-black/50 to-black/30" />
        <div className="relative z-10 w-full max-w-6xl mx-auto px-5 md:px-8 pt-10 md:pt-12 pb-12 md:pb-16">
          <div className="max-w-3xl text-left">
          <p className="text-white/90 uppercase tracking-[0.3em] text-[10px] md:text-xs mb-4 md:mb-5 font-semibold">
            Plan · Drive · Discover
          </p>
          <motion.h1 
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            className="text-[clamp(1.2rem,5.5vw,2.2rem)] sm:text-[2.8rem] md:text-[4.2rem] font-sans font-black tracking-tight text-white mb-4 md:mb-5 leading-[1.03]"
          >
            <span className="block">Your next great</span>
            <span className="block"><span className="text-[#f2a93b]">road trip</span> starts here.</span>
          </motion.h1>
          <motion.p 
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.1 }}
            className="text-base sm:text-lg md:text-[2rem] text-white/95 font-normal tracking-normal max-w-2xl leading-relaxed"
          >
            Build the perfect route, find hidden gems and hit the open road with someone you love.
          </motion.p>
          {!isAdminRoute && !isAboutRoute && (
            <motion.div
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: 0.2 }}
              className="mt-8 md:mt-9 flex flex-wrap items-center gap-3"
            >
              <button
                onClick={() => setActiveView('planner')}
                className={clsx(
                  'px-7 py-3 rounded-lg text-lg font-semibold transition-colors',
                  activeView === 'planner'
                    ? 'bg-[#ef4e2f] text-white hover:bg-[#d84528] shadow-lg shadow-black/20'
                    : 'border border-white/80 text-white bg-white/5 hover:bg-white/15',
                )}
              >
                Plan my trip
              </button>
              <button
                onClick={() => {
                  setHistoryItems(getLocalTripHistory());
                  setActiveView('history');
                }}
                className={clsx(
                  'px-7 py-3 rounded-lg text-lg font-semibold transition-colors',
                  activeView === 'history'
                    ? 'bg-[#ef4e2f] text-white hover:bg-[#d84528] shadow-lg shadow-black/20'
                    : 'border border-white/80 text-white bg-white/5 hover:bg-white/15',
                )}
              >
                My routes
              </button>
              <button
                onClick={() => {
                  void refreshExampleTrips();
                  setActiveView('examples');
                }}
                className={clsx(
                  'px-7 py-3 rounded-lg text-lg font-semibold transition-colors',
                  activeView === 'examples'
                    ? 'bg-[#ef4e2f] text-white hover:bg-[#d84528] shadow-lg shadow-black/20'
                    : 'border border-white/80 text-white bg-white/5 hover:bg-white/15',
                )}
              >
                See examples
              </button>
            </motion.div>
          )}
          </div>
        </div>
      </header>

      <main className="max-w-6xl mx-auto px-4 -mt-20 relative z-20">
        {isAdminRoute ? (
          <section className="glass-card p-8 mb-12 space-y-6">
            <div className="flex items-center justify-between gap-4">
              <h2 className="text-3xl font-serif text-slate-800">Admin: All Users History</h2>
              <button
                onClick={() => {
                  window.history.pushState({}, '', '/');
                  setRoutePath('/');
                }}
                className="text-slate-500 hover:text-slate-700 text-sm underline underline-offset-4"
              >
                Back to front page
              </button>
            </div>

            {!adminUnlocked ? (
              <div className="space-y-3 max-w-md">
                <p className="text-sm text-slate-600">Enter admin password to load all saved trips.</p>
                <input
                  type="password"
                  value={adminPassword}
                  onChange={(e) => setAdminPassword(e.target.value)}
                  className="input-field"
                  placeholder="Admin password"
                />
                <button onClick={handleAdminUnlock} className="btn-primary py-2 px-4 text-sm">
                  Unlock Admin
                </button>
              </div>
            ) : (
              <>
                <div className="flex items-center gap-3">
                  <button onClick={handleAdminRefresh} className="btn-primary py-2 px-4 text-sm" disabled={adminLoading}>
                    {adminLoading ? 'Loading...' : 'Refresh'}
                  </button>
                  <button
                    onClick={() => {
                      setAdminUnlocked(false);
                      setAdminPassword('');
                      setAdminItems([]);
                    }}
                    className="text-slate-500 hover:text-slate-700 text-sm underline underline-offset-4"
                  >
                    Lock
                  </button>
                </div>

                {adminItems.length === 0 ? (
                  <p className="text-slate-600">No trips found in shared history.</p>
                ) : (
                  <div className="space-y-4">
                    {adminItems.map((item) => (
                      <article key={item.id} className="bg-white border border-slate-100 rounded-2xl p-5 space-y-3">
                        <div className="flex flex-wrap items-center justify-between gap-2">
                          <h3 className="text-lg font-semibold text-slate-800">{item.start} to {item.destination}</h3>
                          <div className="flex items-center gap-2">
                            {item.isExample && (
                              <span className="text-[11px] font-semibold uppercase tracking-wide bg-emerald-50 text-emerald-700 px-2 py-1 rounded-full">
                                Example
                              </span>
                            )}
                            <span className="text-xs text-slate-500">{new Date(item.createdAt).toLocaleString()}</span>
                          </div>
                        </div>
                        <p className="text-slate-600 text-sm">User: {item.userId}</p>
                        <p className="text-slate-600 text-sm">{item.summary}</p>
                        <div className="flex flex-wrap gap-4 text-sm">
                          <a href={item.pdfUrl} target="_blank" rel="noopener noreferrer" className="text-romantic-600 hover:text-romantic-700 underline underline-offset-4">
                            Open PDF
                          </a>
                          {item.googleMapsLink && (
                            <a href={item.googleMapsLink} target="_blank" rel="noopener noreferrer" className="text-slate-600 hover:text-slate-800 underline underline-offset-4">
                              Open route in Google Maps
                            </a>
                          )}
                          <button
                            onClick={() => void handleSetExampleTrip(item.id, !item.isExample)}
                            disabled={adminLoading}
                            className="text-slate-600 hover:text-slate-900 underline underline-offset-4 disabled:opacity-50"
                          >
                            {item.isExample ? 'Remove example' : 'Use as example'}
                          </button>
                        </div>
                      </article>
                    ))}
                  </div>
                )}
              </>
            )}
          </section>
        ) : isAboutRoute ? (
          <section className="glass-card p-8 mb-12 space-y-8">
            <div className="flex flex-wrap items-center justify-between gap-4">
              <h2 className="text-3xl font-serif text-slate-800">About ELSK Roadtrip</h2>
              <button
                onClick={() => navigateTo('/')}
                className="text-slate-500 hover:text-slate-700 text-sm underline underline-offset-4"
              >
                Back to front page
              </button>
            </div>

            <p className="text-slate-600 leading-relaxed max-w-3xl">
              ELSK Roadtrip helps couples create memorable journeys with scenic routes, meaningful detours,
              and practical planning support in one place.
            </p>

            <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
              <figure className="bg-white rounded-2xl border border-slate-100 p-4 space-y-3">
                <a href="/Poster-ELSK-Roadtrip-01.png" target="_blank" rel="noopener noreferrer">
                  <img
                    src="/Poster-ELSK-Roadtrip-01.png"
                    alt="ELSK Roadtrip poster"
                    className="w-full h-auto rounded-xl"
                  />
                </a>
                <figcaption className="text-sm text-slate-500">
                  Poster: <span className="font-medium text-slate-700">images/Poster-ELSK-Roadtrip-01.png</span>
                </figcaption>
                <a
                  href="/Poster-ELSK-Roadtrip-01.png"
                  target="_blank"
                  rel="noopener noreferrer"
                  className="inline-flex items-center gap-2 text-romantic-600 hover:text-romantic-700 font-medium underline underline-offset-4"
                >
                  Open fullscreen <ExternalLink size={14} />
                </a>
              </figure>

              <figure className="bg-white rounded-2xl border border-slate-100 p-4 space-y-3">
                <a href="/infographics.png" target="_blank" rel="noopener noreferrer">
                  <img
                    src="/infographics.png"
                    alt="ELSK Roadtrip infographics"
                    className="w-full h-auto rounded-xl"
                  />
                </a>
                <figcaption className="text-sm text-slate-500">
                  Infographics: <span className="font-medium text-slate-700">images/infographics.png</span>
                </figcaption>
                <a
                  href="/infographics.png"
                  target="_blank"
                  rel="noopener noreferrer"
                  className="inline-flex items-center gap-2 text-romantic-600 hover:text-romantic-700 font-medium underline underline-offset-4"
                >
                  Open fullscreen <ExternalLink size={14} />
                </a>
              </figure>
            </div>
          </section>
        ) : (
          <>

        {activeView === 'planner' && (
          <>
        {/* Search Form */}
        <section className="glass-card p-8 mb-12">
          <form onSubmit={handleSubmit} className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
            <div className="space-y-2">
              <label className="text-sm font-semibold text-slate-600 flex items-center gap-2">
                <MapPin size={16} className="text-romantic-500" /> Start location
              </label>
              <input 
                type="text" 
                placeholder="Halden, Norway"
                className="input-field"
                required
                value={formData.start}
                onChange={e => setFormData({...formData, start: e.target.value})}
              />
            </div>
            <div className="space-y-2">
              <label className="text-sm font-semibold text-slate-600 flex items-center gap-2">
                <Navigation size={16} className="text-romantic-500" /> Destination
              </label>
              <input 
                type="text" 
                placeholder="Termoli, Italy"
                className="input-field"
                required
                value={formData.destination}
                onChange={e => setFormData({...formData, destination: e.target.value})}
              />
            </div>
            <div className="space-y-2">
              <label className="text-sm font-semibold text-slate-600 flex items-center gap-2">
                <MapIcon size={16} className="text-romantic-500" /> Waypoints (optional)
              </label>
              <input 
                type="text" 
                placeholder="e.g. Berlin, Munich"
                className="input-field"
                value={formData.waypoints}
                onChange={e => setFormData({...formData, waypoints: e.target.value})}
              />
            </div>
            <div className="space-y-2">
              <label className="text-sm font-semibold text-slate-600 flex items-center gap-2">
                <Clock size={16} className="text-romantic-500" /> Driving hours per day
              </label>
              <input 
                type="number" 
                min="1" 
                max="15"
                className="input-field"
                value={formData.hoursPerDay}
                onChange={e => setFormData({...formData, hoursPerDay: parseInt(e.target.value)})}
              />
            </div>
            <div className="space-y-2">
              <label className="text-sm font-semibold text-slate-600 flex items-center gap-2">
                <Users size={16} className="text-romantic-500" /> Age (optional)
              </label>
              <input 
                type="text" 
                placeholder="45"
                className="input-field"
                value={formData.age}
                onChange={e => setFormData({...formData, age: e.target.value})}
              />
            </div>
            <div className="space-y-2 md:col-span-2">
              <label className="text-sm font-semibold text-slate-600 flex items-center gap-2">
                <Heart size={16} className="text-romantic-500" /> Interests
              </label>
              <input 
                type="text" 
                placeholder="romance, nature"
                className="input-field"
                value={formData.interests}
                onChange={e => setFormData({...formData, interests: e.target.value})}
              />
            </div>
            <div className="lg:col-span-3 grid grid-cols-1 md:grid-cols-[1fr_auto_1fr] items-center gap-4 mt-6 w-full">
              <div className="hidden md:block" />
              <button 
                type="submit" 
                disabled={loading}
                className="btn-primary flex items-center justify-center gap-2 text-lg min-w-[220px]"
              >
                {loading ? (
                  <Loader2 className="animate-spin" size={20} />
                ) : (
                  <Search size={20} />
                )}
                Create Trip Plan
              </button>

              <div className="h-8 flex items-center justify-center md:justify-start md:pl-6 min-w-[320px]">
                <AnimatePresence mode="wait">
                  {loading ? (
                    <motion.p
                      key={loadingMessageIndex}
                      initial={{ opacity: 0, x: 10 }}
                      animate={{ opacity: 1, x: 0 }}
                      exit={{ opacity: 0, x: -10 }}
                      className="text-romantic-600 font-medium italic whitespace-nowrap"
                    >
                      {loadingMessages[loadingMessageIndex]}
                    </motion.p>
                  ) : plan ? (
                    <motion.p
                      initial={{ opacity: 0 }}
                      animate={{ opacity: 1 }}
                      className="text-emerald-600 font-semibold flex items-center gap-2 whitespace-nowrap"
                    >
                      <ChevronDown className="animate-bounce" size={18} />
                      Scroll down for your personalized trip plan
                    </motion.p>
                  ) : null}
                </AnimatePresence>
              </div>
            </div>
          </form>
        </section>

        {/* Results Section */}
        <AnimatePresence mode="wait">
          {plan && (
            <motion.div 
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, y: -20 }}
              className="space-y-12"
            >
              <div className="text-center space-y-4">
                <h2 className="text-4xl font-serif text-slate-800">Your Trip Plan</h2>
                <p className="text-lg text-slate-600 max-w-2xl mx-auto italic">
                  "{plan.summary}"
                </p>
                <div className="flex flex-wrap justify-center gap-4">
                  {plan.googleMapsLink && (
                    <a 
                      href={plan.googleMapsLink} 
                      target="_blank" 
                      rel="noopener noreferrer"
                      className="inline-flex items-center gap-2 text-romantic-600 hover:text-romantic-700 font-medium underline underline-offset-4"
                    >
                      View full route in Google Maps <ExternalLink size={16} />
                    </a>
                  )}
                  <button 
                    onClick={handleSendEmail}
                    className="inline-flex items-center gap-2 text-slate-600 hover:text-slate-800 font-medium underline underline-offset-4"
                  >
                    Send by email <Mail size={16} />
                  </button>
                  <button
                    onClick={handleDownloadPdf}
                    disabled={savingPdf || !plan}
                    className="inline-flex items-center gap-2 text-slate-600 hover:text-slate-800 font-medium underline underline-offset-4"
                  >
                    Download PDF <FileText size={16} />
                  </button>
                </div>
              </div>

              {/* ChatBot Context */}
              <ChatBot plan={plan} />

              {/* Interactive Map Section */}
              <section className="space-y-4">
                <div className="glass-card p-4">
                  <div className="flex items-center justify-between mb-4 px-4 pt-2">
                    <div className="flex items-center gap-2">
                      <MapIcon className="text-romantic-500" />
                      <h3 className="text-xl font-serif text-slate-800">Trip map</h3>
                    </div>
                    {plan.googleMapsLink && (
                      <a 
                        href={plan.googleMapsLink} 
                        target="_blank" 
                        rel="noopener noreferrer"
                        className="btn-primary py-2 px-4 text-sm flex items-center gap-2"
                      >
                        Open in Google Maps <ExternalLink size={14} />
                      </a>
                    )}
                  </div>
                  <InteractiveMap plan={plan} />
                </div>
              </section>

              {/* Detailed Itinerary */}
              <div className="space-y-16">
                {plan.days.map((day, idx) => (
                  <section key={idx} className="space-y-8">
                    <div className="flex items-center gap-4 border-b border-romantic-200 pb-4">
                      <div className="w-12 h-12 rounded-full bg-romantic-600 flex items-center justify-center text-white text-2xl font-serif">
                        {day.day}
                      </div>
                      <div>
                        <h3 className="text-3xl font-serif text-slate-800">Day {day.day}</h3>
                        <p className="text-slate-500 font-medium">{day.route}</p>
                      </div>
                    </div>

                    <div className="grid grid-cols-1 md:grid-cols-2 gap-8 lg:gap-12">
                      {/* POIs for the day */}
                      <div className="space-y-6">
                        <h4 className="text-xl font-serif text-slate-700 flex items-center gap-2 border-l-4 border-blue-400 pl-4">
                          <Camera size={20} className="text-blue-500" /> Attractions & Stops
                        </h4>
                        <div className="space-y-4">
                          {day.pois.map((poi: any, i: number) => (
                            <div key={i} className="bg-white p-6 rounded-2xl shadow-sm border border-slate-100">
                              <div className="flex justify-between items-start mb-2">
                                <h5 className="font-bold text-lg text-slate-800">{poi.name}</h5>
                                {poi.websiteUrl && (
                                  <a 
                                    href={poi.websiteUrl} 
                                    target="_blank" 
                                    rel="noopener noreferrer"
                                    className="text-blue-500 hover:text-blue-600"
                                    title="Visit website"
                                  >
                                    <ExternalLink size={16} />
                                  </a>
                                )}
                              </div>
                              <p className="text-slate-600 text-sm mb-4">{poi.description}</p>
                              <div className="flex items-start gap-2 bg-blue-50 p-3 rounded-xl">
                                <Heart size={14} className="text-blue-500 mt-1 flex-shrink-0" />
                                <p className="text-blue-700 text-xs italic">"{poi.whyForCouple}"</p>
                              </div>
                            </div>
                          ))}
                        </div>
                      </div>

                      {/* Accommodations for the day */}
                      <div className="space-y-6 bg-romantic-50/30 p-4 rounded-3xl -m-4">
                        <h4 className="text-xl font-serif text-slate-700 flex items-center gap-2 border-l-4 border-romantic-400 pl-4">
                          <Hotel size={20} className="text-romantic-500" /> Accommodation suggestions
                        </h4>
                        <div className="space-y-6">
                          {day.accommodations.map((acc: any, i: number) => (
                            <div key={i} className="bg-white rounded-2xl shadow-sm border border-slate-100 overflow-hidden flex flex-col">
                              <div className="grid grid-cols-2 gap-1 h-40 bg-slate-100">
                                {acc.images?.slice(0, 2).map((img: string, imgIdx: number) => (
                                  <img 
                                    key={imgIdx} 
                                    src={img} 
                                    alt={acc.name} 
                                    className="w-full h-full object-cover"
                                    referrerPolicy="no-referrer"
                                  />
                                ))}
                              </div>
                              <div className="relative z-10 p-6 pt-6 bg-white border-t border-slate-100">
                                <div className="flex justify-between items-start gap-4 mb-4">
                                  <div className="min-w-0">
                                    <div className="flex items-center gap-2">
                                      <h5 className="m-0 font-bold text-lg text-slate-800 leading-tight break-words">{acc.name}</h5>
                                      {acc.websiteUrl && (
                                        <a 
                                          href={acc.websiteUrl} 
                                          target="_blank" 
                                          rel="noopener noreferrer"
                                          className="text-romantic-500 hover:text-romantic-600"
                                          title="Visit website"
                                        >
                                          <ExternalLink size={14} />
                                        </a>
                                      )}
                                    </div>
                                    <p className="text-slate-500 text-xs flex items-center gap-1">
                                      <MapPin size={10} /> {acc.location}
                                    </p>
                                  </div>
                                  <div className="text-right shrink-0">
                                    <p className="m-0 text-romantic-700 font-bold text-sm">{acc.priceEstimate}</p>
                                  </div>
                                </div>
                                <p className="text-slate-600 text-xs mb-4 line-clamp-2">{acc.description}</p>
                                <div className="bg-romantic-50 p-3 rounded-xl mb-4">
                                  <p className="text-romantic-700 text-xs italic">"{acc.whyRecommended}"</p>
                                </div>
                                <div className="flex items-center justify-between text-[10px] text-slate-400">
                                  <span>Source: {acc.source}</span>
                                  {acc.websiteUrl ? (
                                    <a 
                                      href={acc.websiteUrl} 
                                      target="_blank" 
                                      rel="noopener noreferrer"
                                      className="text-romantic-600 font-semibold flex items-center gap-1 hover:underline"
                                    >
                                      Book now <ChevronRight size={12} />
                                    </a>
                                  ) : (
                                    <button className="text-romantic-600 font-semibold flex items-center gap-1 opacity-50 cursor-not-allowed">
                                      Book now <ChevronRight size={12} />
                                    </button>
                                  )}
                                </div>
                              </div>
                            </div>
                          ))}
                        </div>
                      </div>
                    </div>
                  </section>
                ))}
              </div>
            </motion.div>
          )}
        </AnimatePresence>
          </>
        )}

        {activeView === 'history' && (
          <section className="glass-card p-8 mb-12 space-y-6">
            <div className="flex items-center justify-between gap-4">
              <h2 className="text-3xl font-serif text-slate-800">Trip History</h2>
              <button
                onClick={() => setHistoryItems(getLocalTripHistory())}
                className="btn-primary py-2 px-4 text-sm"
              >
                Refresh
              </button>
            </div>

            {historyItems.length === 0 ? (
              <p className="text-slate-600">No saved trips yet. Create a plan and click Save PDF.</p>
            ) : (
              <div className="space-y-4">
                {historyItems.map((item) => (
                  <article key={item.id} className="bg-white border border-slate-100 rounded-2xl p-5 space-y-3">
                    <div className="flex flex-wrap items-center justify-between gap-2">
                      <h3 className="text-lg font-semibold text-slate-800">{item.start} to {item.destination}</h3>
                      <span className="text-xs text-slate-500">{new Date(item.createdAt).toLocaleString()}</span>
                    </div>
                    <p className="text-slate-600 text-sm">{item.summary}</p>
                    <div className="flex flex-wrap gap-4 text-sm">
                      <a href={item.pdfUrl} target="_blank" rel="noopener noreferrer" className="text-romantic-600 hover:text-romantic-700 underline underline-offset-4">
                        Open PDF
                      </a>
                      {item.googleMapsLink && (
                        <a href={item.googleMapsLink} target="_blank" rel="noopener noreferrer" className="text-slate-600 hover:text-slate-800 underline underline-offset-4">
                          Open route in Google Maps
                        </a>
                      )}
                    </div>
                  </article>
                ))}
              </div>
            )}
          </section>
        )}

        {activeView === 'examples' && (
          <section className="glass-card p-8 mb-12 space-y-6">
            <div className="flex items-center justify-between gap-4">
              <h2 className="text-3xl font-serif text-slate-800">Example Roadtrips</h2>
              <button
                onClick={() => void refreshExampleTrips()}
                className="btn-primary py-2 px-4 text-sm"
                disabled={examplesLoading}
              >
                {examplesLoading ? 'Loading...' : 'Refresh'}
              </button>
            </div>

            {exampleItems.length === 0 ? (
              <p className="text-slate-600">No example trips yet.</p>
            ) : (
              <div className="space-y-4">
                {exampleItems.map((item) => (
                  <article key={item.id} className="bg-white border border-slate-100 rounded-2xl p-5 space-y-3">
                    <div className="flex flex-wrap items-center justify-between gap-2">
                      <h3 className="text-lg font-semibold text-slate-800">{item.start} to {item.destination}</h3>
                      <span className="text-xs text-slate-500">{new Date(item.createdAt).toLocaleString()}</span>
                    </div>
                    <p className="text-slate-600 text-sm">{item.summary}</p>
                    <div className="flex flex-wrap gap-4 text-sm">
                      <a href={item.pdfUrl} target="_blank" rel="noopener noreferrer" className="text-romantic-600 hover:text-romantic-700 underline underline-offset-4">
                        Open PDF
                      </a>
                      {item.googleMapsLink && (
                        <a href={item.googleMapsLink} target="_blank" rel="noopener noreferrer" className="text-slate-600 hover:text-slate-800 underline underline-offset-4">
                          Open route in Google Maps
                        </a>
                      )}
                    </div>
                  </article>
                ))}
              </div>
            )}
          </section>
        )}
          </>
        )}
      </main>

      {/* Footer */}
      <footer className="mt-20 py-12 border-t border-slate-100 bg-white/50">
        <div className="max-w-6xl mx-auto px-4 text-center">
          <div className="flex items-center justify-center gap-2 mb-4 text-romantic-500">
            <Heart size={20} fill="currentColor" />
            <span className="font-serif text-xl font-bold">ELSK Roadtrip</span>
          </div>
          <p className="text-slate-500 text-sm mb-6">
            Created by ELSK Adventures - with love for unforgettable journeys. <br />
            &copy; 2026 ELSK Adventures. All rights reserved.
          </p>
          <div className="flex flex-wrap justify-center gap-4">
            <button
              onClick={() => navigateTo(isAboutRoute ? '/' : '/about')}
              className="text-slate-400 hover:text-romantic-500 text-xs flex items-center gap-1 transition-colors"
            >
              <ExternalLink size={12} /> {isAboutRoute ? 'Front page' : 'About'}
            </button>
            <button 
              onClick={handleSelectKey}
              className="text-slate-400 hover:text-romantic-500 text-xs flex items-center gap-1 transition-colors"
            >
              <ExternalLink size={12} /> Manage API key
            </button>
          </div>
        </div>
      </footer>
    </div>
  );
}

function DayCard({ day }: { day: any }) {
  const [expanded, setExpanded] = useState(true);

  return (
    <div className="glass-card overflow-hidden">
      <div 
        className="bg-romantic-600 p-6 text-white flex items-center justify-between cursor-pointer"
        onClick={() => setExpanded(!expanded)}
      >
        <div className="flex items-center gap-4">
          <div className="w-12 h-12 rounded-full bg-white/20 flex items-center justify-center text-2xl font-serif">
            {day.day}
          </div>
          <div>
            <h3 className="text-xl font-serif">Day {day.day}</h3>
            <p className="text-white/80 text-sm">{day.route}</p>
          </div>
        </div>
        <motion.div animate={{ rotate: expanded ? 180 : 0 }}>
          <ChevronDown size={24} />
        </motion.div>
      </div>

      <AnimatePresence>
        {expanded && (
          <motion.div 
            initial={{ height: 0, opacity: 0 }}
            animate={{ height: 'auto', opacity: 1 }}
            exit={{ height: 0, opacity: 0 }}
            className="p-8 space-y-10"
          >
            {/* POIs */}
            <section>
              <h4 className="text-2xl font-serif text-slate-800 mb-6 flex items-center gap-2">
                <Camera className="text-romantic-500" /> Attractions & Stops
              </h4>
              <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                {day.pois.map((poi: any, i: number) => (
                  <div key={i} className="bg-slate-50 p-6 rounded-2xl border border-slate-100 hover:border-romantic-200 transition-colors">
                    <h5 className="font-bold text-lg text-slate-800 mb-2">{poi.name}</h5>
                    <p className="text-slate-600 text-sm mb-4">{poi.description}</p>
                    <div className="flex items-start gap-2 bg-romantic-50 p-3 rounded-xl">
                      <Heart size={14} className="text-romantic-500 mt-1 flex-shrink-0" />
                      <p className="text-romantic-700 text-xs italic">"{poi.whyForCouple}"</p>
                    </div>
                  </div>
                ))}
              </div>
            </section>

            {/* Accommodations */}
            <section>
              <h4 className="text-2xl font-serif text-slate-800 mb-6 flex items-center gap-2">
                <Hotel className="text-romantic-500" /> Accommodation suggestions
              </h4>
              <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
                {day.accommodations.map((acc: any, i: number) => (
                  <div key={i} className="flex flex-col bg-white rounded-3xl shadow-sm border border-slate-100 overflow-hidden group">
                    <div className="grid grid-cols-2 gap-1 h-48">
                      {acc.images?.slice(0, 4).map((img: string, imgIdx: number) => (
                        <img 
                          key={imgIdx} 
                          src={img} 
                          alt={acc.name} 
                          className="w-full h-full object-cover"
                          referrerPolicy="no-referrer"
                        />
                      ))}
                    </div>
                    <div className="p-6 space-y-4">
                      <div className="flex justify-between items-start">
                        <div>
                          <h5 className="font-bold text-xl text-slate-800">{acc.name}</h5>
                          <p className="text-slate-500 text-sm flex items-center gap-1">
                            <MapPin size={12} /> {acc.location}
                          </p>
                        </div>
                        <div className="text-right">
                          <p className="text-romantic-600 font-bold">{acc.priceEstimate}</p>
                          <p className="text-[10px] text-slate-400 uppercase tracking-wider">Price estimate</p>
                        </div>
                      </div>
                      
                      <p className="text-slate-600 text-sm line-clamp-3">{acc.description}</p>
                      
                      <div className="space-y-2">
                        <p className="text-xs font-semibold text-slate-400 uppercase tracking-widest">Why we love it</p>
                        <p className="text-slate-700 text-sm italic">"{acc.whyRecommended}"</p>
                      </div>

                      <div className="pt-4 border-t border-slate-50 flex items-center justify-between">
                        <span className="text-xs text-slate-400">Source: {acc.source}</span>
                        <button className="text-romantic-600 text-sm font-semibold flex items-center gap-1 hover:gap-2 transition-all">
                          Check availability <ChevronRight size={16} />
                        </button>
                      </div>
                    </div>
                  </div>
                ))}
              </div>
            </section>
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  );
}
